config/routes.rb
Rails.application.routes.draw do
  root 'decks#index'
  resources :decks do
    resources :cards, only: [:index, :show]
  end
  resources :users

  resources :guesses, only: [:create]

  resources :rounds, only: [:show]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  validates :question, :answer, :deck_id, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  has_many :rounds
  has_many :players, { through: :rounds, source: :user }


   def reset_cards
    self.cards.each do |card|
      card.update_attributes(solved: false)
    end
  end

end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :round
  belongs_to :card

  validates :card_id, presence: true
  validates :round_id, presence: true
end

app/models/round.rb
class Round < ApplicationRecord
  belongs_to :user
  belongs_to :deck
  has_many :guesses
  has_many :cards, through: :deck

  def count_total_guesses
    self.guesses.reduce(0) { |total, guess| total + guess.guess_count }
  end

  def first_try_count
    first_try = self.guesses.select { |guess| guess.guess_count == 1 }
    first_try.length
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :rounds
  has_many :decks, through: :rounds
  has_many :guesses, through: :rounds

  validates :name, :email, presence: true
  validates :name, :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end


end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authorize

  def index
    @deck = Deck.find(params[:deck_id])
    @card = pick_a_card(current_round.cards)
    card_answer = params[:card_answer]
    user_answer = params[:user_answer]
    if !@card.nil?
      redirect_to deck_card_path(@deck, @card, card_answer: card_answer, user_answer: user_answer)
    else
      @round = Round.find(current_round.id)
      redirect_to @round
    end
  end

  def show
    @card_answer = params[:card_answer]
    @user_answer = params[:user_answer]
    @deck = Deck.find(params[:deck_id])
    @card = Card.find(params[:id])
  end


end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authorize, except: [:index]

  def index
    @decks = Deck.all
  end

  def show
    start_round
    @deck = Deck.find(params[:id])
    @deck.reset_cards
    redirect_to deck_cards_path(@deck)
  end
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController
  before_action :authorize

  def create
    @guess = Guess.find_or_create_by(card_id: params[:card_id], round_id: current_round.id)
    @guess.increment!(:guess_count)
    card = Card.find(params[:card_id])
    deck = Deck.find(card.deck_id)
    if answer_check(card, params[:answer])
      card.update_attributes(solved: true)
    end
    redirect_to deck_cards_path(deck, card_answer: card.answer, user_answer: params[:answer])
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authorize

  def show
    @round = Round.find(params[:id])
    @deck = Deck.find(@round.deck_id)
    render 'show'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include GameHelper
end

app/helpers/game_helper.rb
module GameHelper
  def start_round
    round = Round.create(user_id: current_user.id, deck_id: params[:id])
    session[:round_id] = round.id
  end

  def pick_a_card(cards)
    unsolved_cards = cards.select {|card| card.solved == false}
    unsolved_cards.sample
  end

  def current_round
    Round.find(session[:round_id])
  end

  def answer_check(card, user_answer)
    card.answer.downcase == user_answer.downcase
  end
end

app/views/cards/show.html.erb
<p>Hi i'm a card</p>
<% if @card_answer %>
  <p>The correct answer was <%= @card_answer %></p>
  <p>You entered <%= @user_answer %></p>
<% end %>

<%= @card.question %>

<%= form_tag(guesses_path) do %>
  <%= hidden_field_tag(:card_id, @card.id) %>
  <%= label_tag(:user_answer) %>
  <%= text_field_tag(:answer) %>


  <%= submit_tag("Submit") %>

<% end %>

app/views/decks/index.html.erb
<p> Deck List </p>

<% @decks.each do |deck| %>
  <%= link_to deck.name, deck %>
<% end %>

app/views/decks/show.html.erb
<p class="deck">HI i'm a deck</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <% if !current_user %>
      <button class="button"> <%= link_to 'Log in', login_path %> </button>
      <button class="button"> <%= link_to 'Register', new_user_path %> </button>
    <% else %>
       <%= link_to "#{current_user.name}", user_path(current_user) %> <button class="button"> <%= link_to 'Logout', logout_path %> </button>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/rounds/show.html.erb
<table>
  <tr>
    <th>Deck Name</th>
    <th>Correct on first try</th>
    <th>Total guesses</th>
  </tr>
  <tr>
    <td> <%= @deck.name %> </td>
    <td> <%= @round.first_try_count %> </td>
    <td> <%= @round.count_total_guesses %> </td>
  </tr>
</table>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </p>
  <p>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </p>
  <p>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </p>
  <p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  </p>
  <p>
  <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h2> Welcome home, <%= @user.name %> </h2>

<% @user.rounds.each do |round| %>
<h3>  <%= round.deck.name %> </h3>
<table>
  <tr>
    <th>Date</th>
    <th>Cards in deck</th>
    <th>First Guess Correct</th>
    <th>Total Guesses</th>
  </tr>
  <tr>
    <td> <%= round.updated_at %> </td>
    <td> <%= round.cards.length %> </td>
    <td> <%= round.first_try_count %> </td>
    <td> <%= round.count_total_guesses %> </td>
  </tr>
</table>
<% end %>